### ISSUE TITLE
Prometheus causes panic when re-starting stopped VM

### ISSUE THREAD

**Issue by twelho** [weaveworks/ignite#102]
Tested by calling `ignite run -i weaveworks/ignite-ubuntu` -> `reboot` and then trying to start the VM again using `ignite start -id <name>`. `ignite-spawn` crashes with the following:
```go
panic: listen unix /var/lib/firecracker/vm/6a2b6ebafcb0e75c/prometheus.sock: bind: address already in use
```

**Comment by luxas** [comment]
Fixed with ef49edd5397390c0f0606364dc608b5b3fd4a186
