### ISSUE TITLE
Can't ssh to machine with prefixed name

### ISSUE THREAD

**Issue by alexellis** [weaveworks/ignite#121]
This isn't an ambiguous name, it is an exact match, but I can't use "my-vm" because I have "my-vm-2"

Hope this is enough info

```
alex@nuc7:~/go/src/github.com/openfaas/faas-netes$ sudo ignite ssh my-vm
ambiguous VM query: "my-vm" matched the following IDs/names: my-vm-2, my-vm
```

**Comment by alexellis** [comment]
Even when I did correct the name, it still failed to log in with centos - connection refused.

Ubuntu worked though:

```
ignite run weaveworks/ignite-ubuntu \
    --cpus 2 \
    --memory 1GB \
    --ssh \
    --name my-vm
```

Might be worth updating the `ignite run` example to use the above in that case?

**Comment by luxas** [comment]
Right, I think the code that also respected exact matches was unintentionally refactored away :sweat_smile:. Let's fix it!

> centos - connection refused.

I've experienced that centos takes some more time than Ubuntu to initialize SSH. I'll open a new issue for better SSH UX (retries and custom error messages)

**Comment by twelho** [comment]
The code doing exact matches wasn't removed, but since it's called for each object individually and not tracked in the filters, it has no effect. Will move it to the IDNameFilter so we get it working again.

**Comment by twelho** [comment]
In the meantime, you can use the VM's ID (or a prefix of it) to select the correct VM.

**Comment by twelho** [comment]
Fixed in PR https://github.com/weaveworks/ignite/pull/138, thanks for noticing this @alexellis!
