### ISSUE TITLE
Actually check that the container started when running `ignite start`

### ISSUE THREAD

**Issue by luxas** [weaveworks/ignite#124]
Check e.g. that the `prometheus.sock` file appears, and first then exit.
Have a timeout of e.g. 5-10 seconds (other than that is very strange for the container to start).
In general, we need some kind of communication channel between the CLI and `ignite-spawn`

**Comment by twelho** [comment]
>Check e.g. that the prometheus.sock file appears, and first then exit.
This is now implemented in https://github.com/weaveworks/ignite/pull/139.
