### ISSUE TITLE
"ignite images" -> Object 'Kind' is missing in 

### ISSUE THREAD

**Issue by alexellis** [weaveworks/ignite#127]
Despite being able to run an image, I did get this error when running `ignite images`:

```
root@nuc7:~# ignite kernels
KERNEL ID		NAME					CREATED		SIZE	VERSION
997e693af332bfd6	weaveworks/ignite-kernel:4.19.47	5h31m ago	49.0 MB	4.19.47
root@nuc7:~# 
root@nuc7:~# ignite images
Object 'Kind' is missing in '{
    "ID": "7f9feb5d10321f01",
    "Name": "weaveworks/ignite-ubuntu:latest",
    "Type": "image",
    "Created": "2019-07-10T10:23:02Z",
    "ObjectData": {}
}
'
root@nuc7:~# ignite version
Ignite version: version.Info{Major:"0", Minor:"4", GitVersion:"v0.4.0", GitCommit:"e0e7e8c50cd3c6532486625393dff4d415081829", GitTreeState:"clean", BuildDate:"2019-07-10T12:30:11Z", GoVersion:"go1.12.1", Compiler:"gc", Platform:"linux/amd64"}
Firecracker version: v0.17.0
root@nuc7:~# 
```

Is there a reset or a fix for this?

Alex

**Comment by twelho** [comment]
Try to remove the `/var/lib/firecracker` directory and run the VM again, the file formats have changed between v0.3.0 and v0.4.0 causing these kinds of issues.

**Comment by luxas** [comment]
Hi @alexellis :wave:, thanks for trying Ignite out!

Yes, echoing what @twelho said, sorry that we hadn't updated the installation docs to point installing to v0.4.0 at the point you did the installation. The underlying data format changed in an inbackwards-compatible way between v0.3.0 -> v0.4.0. Now from v0.4.0 and onwards, we have a plan to automatically support upgrading between versions.

The solution is, uninstalling Ignite as per [here](https://github.com/weaveworks/ignite/blob/master/docs/installation.md#removing-the-installation), or alternatively manually going in and doing 

```
rm -r /var/lib/firecracker/(vm|image|kernel)/$uid
```
in this case:

```
rm -r /var/lib/firecracker/image/7f9feb5d10321f01
```

I'm closing this issue as we now have the right installation docs in place, pointing to v0.4.0, and we don't support v0.3.0 anymore.
