### ISSUE TITLE
Mention kvm-ok / the `cpu-checker` package in installation docs

### ISSUE THREAD

**Issue by luxas** [weaveworks/ignite#141]
ref: https://github.com/weaveworks/ignite/pull/118#issuecomment-510657373

From @alexellis:
>  I wonder if you can install kvm-ok without installing a load of other packages for libvirt?

From @luxas:
> I just checked that yes, you can get it via a apt-get install cpu-checker, without libvirt deps.

We should add a step to do `apt-get install cpu-checker` (or similar for rpms) to the installation.md doc

**Comment by alexellis** [comment]
sgtm

**Comment by alexellis** [comment]
Btw.. not sure if you've seen Derek yet, but he can help manage milestones, labels, issues, PRs etc (some features are optional too) - it's good for collaboration and for using the mobile interface which doesn't expose those buttons. There's a SaaS / app version too https://github.com/alexellis/derek/blob/master/GET.md https://github.com/alexellis/derek/blob/master/USER_GUIDE.md

**Comment by saiyam1814** [comment]
true, KVM is mandatory to check for ignite and can save a lot of time for new folks if they realize it before setting up ignite and try to run.

**Comment by luxas** [comment]
Put a fix up for this #145
