### ISSUE TITLE
Flag for setting the SSH key generation algorithm

### ISSUE THREAD

**Issue by twelho** [weaveworks/ignite#152]
In FIPS-enabled machines the `ed25519` key generation algorithm is unavailable, so they need to use `rsa`.
- Let the user specify the algorithm to use via a flag during VM creation
- Improve autodetection for FIPS machines to automatically switch over to `rsa`
- Enforce a specific key length (between 2048 and 4096) when using `rsa`

**Comment by luxas** [comment]
Related/similar to #150

**Comment by luxas** [comment]
I'm closing this in favor for #185
