### ISSUE TITLE
Created and not started VM is not shown in the list

### ISSUE THREAD

**Issue by arun-gupta** [weaveworks/ignite#157]
Created an Ignite VM as:

```
ignite create weaveworks/ignite-ubuntu \
		--name my-vm \
		--cpus 2 \
		--memory 1GB \
		--size 6GB \
		--ssh
```

`ignite vm ls` does not show VM in the list:

```
root@ip-172-31-6-217:~# ignite vm ls
VM ID	IMAGE	KERNEL	CREATED	SIZE	CPUS	MEMORY	STATE	IPS	PORTS	NAME
```

Started the VM as:

```
ignite vm start my-vm
```

And now the command shows the VM in the list:

```
ignite vm ls
VM ID			IMAGE				KERNEL					CREATED		SIZE	CPUS	MEMORY		STATE	IPS	PORTS	NAME
3feb8e0be0b1a4bc	weaveworks/ignite-ubuntu:latest	weaveworks/ignite-kernel:4.19.47	2m30s ago	6.0 GB	2	1024.0 MB	Running	172.17.0.2		my-vm
```

Created VM with the correct `STATE` should be shown there.

**Comment by curx** [comment]
have you tried the run like `docker`, run = create + start:
see https://github.com/weaveworks/ignite/blob/master/docs/cli/ignite_create.md
and https://github.com/weaveworks/ignite/blob/master/docs/cli/ignite_run.md

**Comment by curx** [comment]
e.g. `ignite create` is an alias for `ignite vm create`

**Comment by arun-gupta** [comment]
`ignite vm ls` works after `ignite run`. Is it not expected to work after `ignite create`?

**Comment by luxas** [comment]
`ignite vm ls` does, at the moment the same as `ignite ps` (shows only running VMs). However, as pointed out by @arun-gupta, that's not very intuitive, as `ls` is meant to show everything, whereas `ps` only running stuff.

Let's change this to make `vm ls` show both running and stopped VMs.
Any volunteers for PRs?
A new dedicated `ls` command needs to be added here, that always sets the `-a` switch to true: https://github.com/weaveworks/ignite/blob/master/cmd/ignite/cmd/vmcmd/ps.go#L14

**Comment by twelho** [comment]
I made the required changes in https://github.com/weaveworks/ignite/pull/179, `ignite vm ls/list` are both just aliases for `ìgnite vm ps` to avoid duplicate code, with the pull request above `ps` now detects if it's being called via `ls` or `list` and lists all VMs instead of just running ones accordingly.
