### ISSUE TITLE
[QUESTION] could i use ignite as CRI runtime for kubelet?

### ISSUE THREAD

**Issue by Slach** [weaveworks/ignite#162]
could somebody add to documentation howto use ignite as CRI in Kubernetes? for running firecracker VM instead of containers with namespaces?

**Comment by luxas** [comment]
Let's add this question to the coming FAQ.md (#147).

In short, no, you can't use Ignite as a CRI runtime, as it doesn't run containers.
Ignite runs real VMs, based on a OCI image's rootfs.

If you want to run containers with Firecracker isolation, check out https://github.com/firecracker-microvm/firecracker-containerd.

Also some more info on this thread: https://twitter.com/jschnatterer/status/1150042240888332288

I'll keep this open until we have this in the FAQ.

**Comment by luxas** [comment]
This is now fixed with #197
