### ISSUE TITLE
missing /etc/resolv.conf

### ISSUE THREAD

**Issue by BenTheElder** [weaveworks/ignite#164]
So far with both the centos and ubuntu weaveworks images for ignite when I start a VM network connectivity seems to be fine, except I cannot lookup any hostnames. Creating a trivial `/etc/resolv.conf` with `nameserver 8.8.8.8` solves this and makes it a lot easier to work inside the VMs.

Docker and Kubernetes are both known to create / manage this file based on the hosts resolver settings and user options, it might be nice if ignite behaved similar to docker here.

Alternatively, if we don't want to do this and want to leave it out of the scope for `ignite`, it will probably be friendlier to new users if the default images ship a simple resolv.conf with at least one nameserver so package management, wget, etc. work.

**Comment by luxas** [comment]
Yes, this is a known issue we discovered the other day. It was working before, but we seem to have got a regression in the latest week or so.

We always did intend to write the right `/etc/resolv.conf` as per how the container was set up (we have code for this). We'll fix this issue ASAP in v0.4.2 :smile:

**Comment by BenTheElder** [comment]
Thanks!
