### ISSUE TITLE
macOS support?

### ISSUE THREAD

**Issue by prologic** [weaveworks/ignite#165]
is support for macOS supported or planned?

I successfully compiled the `ignite` client CLI on macOS; but the `ignite-spawner` seems to have some assumed Linux-isms in the code that fail to compile on macOS.

The reason I ask is it would be convenient for local development of ignore itself as well as local development against ignore vm based application development.

**Comment by luxas** [comment]
At the moment, Ignite requires a linux kernel to execute successfully, as it sets up the VM prereqs in certain ways (e.g. with devicemapper). Eventually, as we have a daemon (#33), it will take care of those things, and the Ignite CLI can operate anywhere, as _just_ a CLI.

Firecracker however, will always require to run on Linux. It's specifically built for the linux kernel and KVM. So unless you somehow boot a VM on your Mac, running Linux, with support for nested virtualization, it can't be done. And running a VM with linux (with e.g. vagrant) pretty much defeats the purpose. I don't know. 

More info about what Ignite/Firecracker requires is here: https://github.com/weaveworks/ignite/blob/master/docs/dependencies.md

What do you think?

**Comment by prologic** [comment]
Thanks for the quick and detailed response! Much of what I expected.

#33 is what I was really after (_sorry I didn't see this before_).

**Comment by luxas** [comment]
You're welcome :smile:
Is there anything more we need to do here, or can we close this issue?

**Comment by prologic** [comment]
Go ahead! I'll subscribe to #33 Thanks 😀
