### ISSUE TITLE
Avoid nil panics around ObjectMeta.Created

### ISSUE THREAD

**Issue by luxas** [weaveworks/ignite#169]
During the TGIK session, Joe created a VM object without `metadata.created` set in the VM object in Git (totally reasonable!), and when running `ignite ps -a`, ignite paniced.

This tells us two things:
a) Always check if `.Created` is nil before using (in `ps` output etc). (There might be that there are no such cases, but check)
b) If `nil` is given to `util.output.Write()`, write an empty string instead of panicing
c) In storage, instead of checking if the file exists already, always set `.Created` if it is `nil`

**Comment by twelho** [comment]
How about having a custom encoder/decoder for the `Time` type, which would handle setting the creation time if it's blank? `omitempty` and a pointer are unnecessary, as the creation timestamp needs to _always_ exist. This way if the creation timestamp is blank, it would set it right when Ignite first begins operating the file and it can be safely omitted without having to implement nil pointer checks everywhere.

**Comment by luxas** [comment]
Hmm, I think that should work, too. Go ahead and we'll see how it starts to look

**Comment by twelho** [comment]
Here's the work for this approach: https://github.com/weaveworks/ignite/pull/174

**Comment by luxas** [comment]
Fixed with https://github.com/weaveworks/ignite/pull/174
