### ISSUE TITLE
Encode/decode meta.UID without ""

### ISSUE THREAD

**Issue by luxas** [weaveworks/ignite#170]
This bug/oversight was noticed during the TGIK session. Joe tried to set `.metadata.uid=1234` (which should work), but the JSON parser errored that it must have `"` around it as it's decoded into a string.

We should fix this to allow decoding both with and without `"` around the value, but always encode without `"`, to be consistent with the name.

**Comment by twelho** [comment]
Resolved in https://github.com/weaveworks/ignite/pull/178.
