### ISSUE TITLE
Add arm64 support

### ISSUE THREAD

**Issue by luxas** [weaveworks/ignite#172]
Firecracker has added alpha arm64 support, let's get that going for Ignite too, so we can test it

Hoping to get this also working on a RPi 3/4 :100: :smile:

**Comment by vielmetti** [comment]
My understanding from talking to @dieterreuter is that Firecracker's arm64 support depends on GICv3, and that the Pi 3/4 have only GICv2. That said, the arm64 servers at Packet have GICv3 and I'm also interested in this and interested in helping test.

**Comment by luxas** [comment]
Awesome @vielmetti! Then I could try to get the arm64 builds working this week (#173), so we can get this into the next release, v0.5.0.

**Comment by vielmetti** [comment]
@twelho thanks for merging this in - just to be sure I know what's in #173, this covers building Ignite for arm64, but not yet the GICv2 support specific to the Raspberry Pi mentioned above?

**Comment by luxas** [comment]
> @twelho thanks for merging this in - just to be sure I know what's in #173, this covers building Ignite for arm64, but not yet the GICv2 support specific to the Raspberry Pi mentioned above?

Right, but with this you should be able to run it on Packet.
For RPi support we need upstream Firecracker to change code...
I will do an alpha release of v0.5.0 next week so you have some "official" arm64 binaries to test
cc @dieterreuter

**Comment by vielmetti** [comment]
@luxas nice! When 0.5.0 arrives I will make a point to test it at Packet and report back.
