### ISSUE TITLE
Provide "Preflight checks" to Ignite

### ISSUE THREAD

**Issue by luxas** [weaveworks/ignite#184]
Before trying to run a VM, make sure that we have a set of dependencies on the host, e.g. `/dev/kvm` available. Otherwise, fail fast. This would pretty much mimic the [kubeadm preflight checks](https://github.com/kubernetes/kubernetes/blob/master/cmd/kubeadm/app/preflight/checks.go) on an abstract level.

**Comment by luxas** [comment]
Hi @andrewrynhard :wave:, could you help us make this happen as discussed :smile:?

**Comment by andrewrynhard** [comment]
Would be happy to. I need to find a machine that I can get ignite working on. Maybe I will spin up a machine in packet. Not sure if other clouds support nested virtualization.

**Comment by stealthybox** [comment]
Notable that a user should be able to opt-out of pre-flight checks.
ex:  the kernel-config check isn't always possible -- not all hosts will have an introspect-able config.
The user should still be able to move forward without one.

**Comment by najeal** [comment]
Discovering the project, regarding the `ContainerConfig` I made a list of needed preflight checks:

- ports availability
- /dev/mapper/control
- /dev/net/tan
- /dev/kvm
- existing metadata.json file
- existing vmlinux file

Let me know if you see anything that should be added/removed to the preflight.

@stealthybox, if we follow the "same behavior" as the link given by @luxas we can choose to exclude specific checks when needed.

**Comment by luxas** [comment]
Sounds awesome @najeal! Go for it :clap:!
