### ISSUE TITLE
Create a website with documentation

### ISSUE THREAD

**Issue by luxas** [weaveworks/ignite#207]
Using Netlify, MkDocs or ReadTheDocs for example.
I like how the https://eksctl.io site is created, and would be very happy to do the same thing for Ignite.

**Comment by dholbach** [comment]
https://github.com/weaveworks/flux/pull/2152 could serve as an example.

**Comment by luxas** [comment]
Reopening this until we have a public read-the-docs endpoint (and/or a custom domain).
@dholbach can you make this happen?

**Comment by dholbach** [comment]
https://ignite.readthedocs.io/en/latest/ is live!

**Comment by luxas** [comment]
Thank you!! Then we're done here :smile:

**Comment by dholbach** [comment]
Can this issue be closed and we track all upcoming bits in new issues?

**Comment by dholbach** [comment]
Ah yes. :-D
