### ISSUE TITLE
DNS Not Setup Correctly from Ubuntu Host

### ISSUE THREAD

**Issue by robertojrojas** [weaveworks/ignite#213]
-  Ignite **latest-v0.4.2**
-  Ubuntu **18.04** Host
- weaveworks/ignite-kubeadm **latest-v0.4.2**

**Steps**
- Clean Docker
   `docker images`
   `REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE`
- Install Ignite **latest-v0.4.2**
- Run Test VM
  `ignite run weaveworks/ignite-kubeadm:latest-v0.4.2 \
    --cpus 2 \
    --memory 1GB \
    --ssh \
    --name test-vm-v0.4.2
     `
- ignite ssh test-vm-v0.4.2
- Test for Empty `/etc/resolv.conf`
 `[ -s /etc/resolv.conf ] || echo '/etc/resolv.conf is empty'`

**Comment by aojea** [comment]
seems a duplicate of this https://github.com/weaveworks/ignite/issues/164

**Comment by luxas** [comment]
Hi! Can you please remove the base/kernel image you're using with `ignite rmi` and `ignite rmk`, and try again with v0.4.2?

There was an issue in v0.4.0 and v0.4.1 that made the kernel overlay overwrite `/etc/resolv.conf` accidentally. Hence the kernel image needs to be removed and recreated after upgrading to v0.4.2.

**Comment by aojea** [comment]
awesome, it works now

**Comment by robertojrojas** [comment]
Yes, the steps of removing both the image and kernel made it work. Thanks @luxas!
