### ISSUE TITLE
Add Support to Filter VMs

### ISSUE THREAD

**Issue by robertojrojas** [weaveworks/ignite#228]
It would nice if one could execute a command like:
    `ignite ps --filter <search>`

   example:
     `ignite ps --filter "label=k8s-cluster"`

This could work similarly to [Docker ps](https://docs.docker.com/engine/reference/commandline/ps/)

**Comment by curx** [comment]
or another filter like `--filter state=running|stopped|created`

**Comment by luxas** [comment]
Yes, this would be nice to have :smile:
The underlying object is a normal Go struct, so it should be possible to take in a Go template e.g. `{{.Status.State}}=Running` or similar.
Help wanted if you want to contribute :wink:

**Comment by chanwit** [comment]
/contributor-assign @najeal
Thank you for looking at it :-)
