### ISSUE TITLE
makefile does not ensure output directories

### ISSUE THREAD

**Issue by BenTheElder** [weaveworks/ignite#230]
`make tidy`, will fail due to `./bin/cache/go/bin` not existing. in general the make commands depend on directories that will not exist in a clean development environment and do not ensure that they exist.

**Comment by BenTheElder** [comment]
Addtionally, after writing a patch for this, it seems `goimports` must be installed on the host.

I would tentatively suggest something like creating a hack/tools go module to track development tools and install these to bin/ from the module instead of using whatever the host has installed.

**Comment by BenTheElder** [comment]
besides `goimports`, `make tidy` also depends on `sfdp` (graphviz?), I suppose we should just document this in devel? or possibly it could be run via a container?

**Comment by luxas** [comment]
Thanks! Fixed with #231. @twelho is now fixing the `graphviz` doc issue. Closing this :)

**Comment by BenTheElder** [comment]
Thanks!
