### ISSUE TITLE
Add support for `rkt` as a container runtime

### ISSUE THREAD

**Issue by taqtiqa-mark** [weaveworks/ignite#237]
[Rkt](https://github.com/rkt/rkt) is stable and allows one to avoid all the docker cruft.

**Comment by luxas** [comment]
Hi @taqtiqa-mark :wave:!
Yes, we do plan to have a swappable container runtime interface (see e.g. #209)
What's a bit concerning to me though is that rkt seems to be pretty unmaintained, unfortunately...

**Comment by taqtiqa-mark** [comment]
Thanks for the pointer to #209.  Rkt is stable and feature complete for downloading, launching and stopping containers.  Consistent with the reasons for its creation, it has not been chasing every shiny new thing, nor trying to 'rule-them-all'.

<pet-peeve-rant>It would be welcome development if projects started putting as much effort into supporting existing, working, tech stacks as a first priority.  Rather than chasing the latest evolving (unstable [in terms of end state]) projects.</pet-peeve-rant>

Acknowledge that Rkt is being archived in CNCF, but remains open at github.com/rkt/rkt.

**Comment by luxas** [comment]
Right, I understand what you mean. It won't be a priority for us; but we'd happily receive contributions towards this end of supporting it as a runtime through the interface.

Would you be up for adding that support?
Do you know if `rkt` supports CNI?

**Comment by taqtiqa-mark** [comment]
Unfortunately integrating Rkt is outside my current skillset.  Happy to close this issue since it's not on any roadmap.
