### ISSUE TITLE
Master branch is broken due to multi-arch support

### ISSUE THREAD

**Issue by praseodym** [weaveworks/ignite#273]
Executing `make build-all` builds the ignite Docker image as
`docker tag weaveworks/ignite:dev weaveworks/ignite:v0.4.0-340-0b0806b515f369-arm64`, whereas running a VM still expects the image tag without arch suffix:
```
INFO[0002] Pulling image "weaveworks/ignite:v0.4.0-340-0b0806b515f369"...
FATA[0004] Error response from daemon: manifest for weaveworks/ignite:v0.4.0-340-0b0806b515f369 not found: manifest unknown: manifest unknown
```

**Comment by twelho** [comment]
Indeed, thanks for noticing this!
Fixed in https://github.com/weaveworks/ignite/pull/274.
