### ISSUE TITLE
[vagrant] Archiving an Ignite VM

### ISSUE THREAD

**Issue by taqtiqa-mark** [weaveworks/ignite#287]
What would the contents of a complete Ignite VM archive look like (files and folder structure)?

Context:
Complement a Vagrant plugin (issue #190).  
The ideal is that a user would execute, for example, `vagrant box add <org>/ubuntu-18.04`
and obtain all files required to launch a fully isolated Ignite VM - without further downloads.  

Out-of-scope for this issue, but giving additional context: 
In turn the archived/packed Ignite VM would contain the bare minimum of software for Vagrant to function (package manager, ssh, ssh user).  
A feature of the Ignite VM is that it may be possible to have a base box that excludes ssh (?).

Comparisons:
For VirtualBox the box format/content is just a flat directory of the contents of a `VBoxManage export` command 
For VMWare Fusion box format/content is just a flat directory of the contents of a `vmwarevm` folder.
For AWS the box format/content is just a Vagrantfile defaulting some configuration.

**Comment by stealthybox** [comment]
@taqtiqa-mark Thanks for putting these detailed issues together :wave: 

The ignite equivalent of `vagrant box add` is:
```
ignite image import <OCI image>
ignite kernel import <OCI image>
```

Ignite also depends on the container runtime having `weaveworks/ignite:${version}` available.
This container image is use to start the `ignite-spawn` sandbox required for all vm's.

If you have the VM base image and kernel images imported, and the runtime has the sandbox image, no downloads are necessary.

**Comment by taqtiqa-mark** [comment]
Thanks for the feedback.  I'm still getting my head around the best way to tackle this:
```
ignite image import <OCI image>
ignite kernel import <OCI image>
```
Presumably, both result in some artifacts stored on the local HDD?
If so, what does that folder/file manifest look like and will it be stable, or ignite version dependent?

If `vagrant box add <...>` replicated that folder/file structure would ignite be happy, or abdend at launch time?

**Comment by stealthybox** [comment]
I imagine `vagrant box add` should exec `ignite` and pass the box reference as an OCI image argument to the command.
Were you thinking something else?

How do the docker vagrant runtimes work with images?

**Comment by taqtiqa-mark** [comment]
The docker provider in vagrant doesn't use a Box file.  It'll either take:
- Path to a Dockerfile.
- image name.
- gitrepo refe toa Docker file.

I'd like the ignite provider to be independent of Docker as far as possible (what is possible being defined by ignite core).  Ideally the provider should Ignorant of the container lauch mechanism - Ignite upstream can change that and (assuming the local ignite works) the vagrant plugin should just work unchanged. 

The vagrant provider should work in air-gapped environments where any OCI container requirements are  in place and assumed working.  This means shelling out isn't really an option and gets messy/buggy fast.

It sounds like inserting a VM into ignite is more complex than a file copy workflow?

**Comment by taqtiqa-mark** [comment]
After some experience building [chef-ignite](https://github.com/BegleyBrothers/chef-ignite) I now believe the sustainable path is to either use [upstreams firectl](https://github.com/firecracker-microvm/firectl), libvirt (if a firecracker provider emerges) or firecracker directly.
