### ISSUE TITLE
Feature: ignite image import ./some/local/file/path

### ISSUE THREAD

**Issue by taqtiqa-mark** [weaveworks/ignite#291]
Use case Vagrant plugin (issue #190 )
```
ignite image import ./some/local/file/path
```

Perhaps support `file ://` URI scheme?

Vagrant has the notion of a 'base box' which is the components required to run a VM from Vagrant.
With Vagrant offering an abstraction layer it would be best to package a 'Vagrant base-box' that contained known to work:

1. Linux Kernel.
1. Container Image.
1. Ignite managed VM (i.e. a Firecracker microVM).

Bearing in mind many Vagrant users would be using this provider as one component of a tech stack devoted to other dev work (web pages, API).... they will likely not be current with the working permutations of the above 3 components.

This would prevent questions such as issue #290.

**Comment by nathanielknight** [comment]
I think this feature would make Ignite very compelling for doing git-ops in certain settings (e.g. hobbyists; small-scale, high-assurance environments).

**Comment by taqtiqa-mark** [comment]
After some experience building [chef-ignite](https://github.com/BegleyBrothers/chef-ignite) I now believe the sustainable path is to either use [upstreams firectl](https://github.com/firecracker-microvm/firectl), libvirt (if a firecracker provider emerges) or firecracker directly.
