### ISSUE TITLE
Importing large images doesn't work

### ISSUE THREAD

**Issue by luxas** [weaveworks/ignite#295]
As reported by @neith00 (IIRC) on Slack.

If you import a large-ish image (e.g. ~900MB), `ignite` fails strangely with:

```
# ignite create node
INFO[0000] Starting image import...                     
FATA[0010] exit status 2
```

It seems to timeout after ten seconds when importing; although the importing process of a larger image requires more time (naturally).

cc @twelho

**Comment by luxas** [comment]
This has been present already in v0.4.x, so it's not a release blocker for v0.5.0. We'd like to fix it in a v0.5.x patch release, though.

**Comment by alex-leonhardt** [comment]
not sure if there was/is a fix in master but I've just tried this (I had built `ignite` from master) and I cannot reproduce this anymore .. the example isn't my image but it's ~912MB so large enough that it should've triggered the issue .. 

```
vagrant@ubuntu-bionic:/vagrant/bin/amd64$ sudo ./ignite image import mbopm/activemq:latest
INFO[0000] Docker image "mbopm/activemq:latest" not found locally, pulling... 
INFO[0092] Starting image import...                     
INFO[0132] Imported OCI image "mbopm/activemq:latest" (912.0 MB) to base image with UID "08b1f641cf98da3a" 
INFO[0132] Created image with ID "08b1f641cf98da3a" and name "mbopm/activemq:latest" 
vagrant@ubuntu-bionic:/vagrant/bin/amd64$ free -m 
              total        used        free      shared  buff/cache   available
Mem:            985         136         243           0         604         697
Swap:             0           0           0
vagrant@ubuntu-bionic:/vagrant/bin/amd64$ sudo ./ignite image import mbopm/activemq
INFO[0000] Created image with ID "08b1f641cf98da3a" and name "mbopm/activemq:latest" 
vagrant@ubuntu-bionic:/vagrant/bin/amd64$ sudo ./ignite image import mbopm/activemq:5.12.1
INFO[0000] Docker image "mbopm/activemq:5.12.1" not found locally, pulling... 
INFO[0015] Starting image import...                     
INFO[0057] Imported OCI image "mbopm/activemq:5.12.1" (912.0 MB) to base image with UID "e2ae14049c239993" 
INFO[0057] Created image with ID "e2ae14049c239993" and name "mbopm/activemq:5.12.1" 
```

FWIW - my initial thought was that [`(ds *DockerSource) Reader()`](https://github.com/weaveworks/ignite/blob/master/pkg/source/docker.go#L82)
used by [func addFiles(img *api.Image, src source.Source)](https://github.com/weaveworks/ignite/blob/master/pkg/dmlegacy/image_format.go#L60) is potentially eating up all the memory whilst reading in/passing the entire image but that didn't hold, so maybe it's _"fixed"_ already  - _or_ -  it may have something to do with the size of the layers which I haven't tried yet.

**Comment by alex-leonhardt** [comment]
So I managed to break it by using 2 x 1gb layers and also timed it and took ~27 seconds to trigger the issue ..
```
vagrant@ubuntu-bionic:/vagrant/bin/amd64$ free -m; time sudo ./ignite image import local/2000mb:latest; free -m;
              total        used        free      shared  buff/cache   available
Mem:            985         159         258           0         568         680
Swap:             0           0           0
INFO[0000] Starting image import...                     
FATA[0027] exit status 2                                

real    0m27.383s
user    0m1.669s
sys     0m8.688s
              total        used        free      shared  buff/cache   available
Mem:            985         161         159           0         664         682
Swap:             0           0           0
```

the Dockerfile is 
```
FROM scratch
ADD 1000mb.dd /1.dd
ADD 1000mb.dd /2.dd
```

the `.dd` files were created with 
```
dd if=/dev/urandom of=./1000mb.dd bs=1M count=1000
```

**Comment by twelho** [comment]
After some debugging it seems the issue is the block device size allocation. Currently we make the ext4 block device the size of the contents as reported by Docker + 100 MB. With more contents the ext4 journal and other metadata require more than our 100 MB buffer and the device runs out of space, resulting in exit status 2.
