### ISSUE TITLE
Create a "stable" Read The Docs branch

### ISSUE THREAD

**Issue by luxas** [weaveworks/ignite#318]
cc @dholbach 
we'll do this for v0.5.1, after v0.5.0 has been cut so we have something "stable" :)
we need to update all references in e.g. the README

**Comment by dholbach** [comment]
Setting this up in the readthedocs.io UI is very simple - just point to whatever your stable branch is going to be.

**Comment by luxas** [comment]
Yes, will do later

**Comment by luxas** [comment]
This is now fixed. ignite.readthedocs.org now automatically points to the stable branch, too

**Comment by luxas** [comment]
Oh, right, we should update the README.
@twelho can you do that?
