### ISSUE TITLE
ignite-spawn timing out (master)

### ISSUE THREAD

**Issue by alex-leonhardt** [weaveworks/ignite#339]
I built ignite from master using 
```
make build-all
```

and when trying to run a vm
```
ignite start 961caa578839a27c
```

then it times out starting up 
```
INFO[0000] Networking is handled by "docker-bridge"     
INFO[0000] Started Firecracker VM "961caa578839a27c" in a container with ID "28f6578fb990b2dfc2b8bf223d4e1829112aaafb7d8830ee90f875b6f17dd826" 
FATA[0010] timeout waiting for ignite-spawn startup     
```

the logs show 
```
docker logs 28f6578fb990b2dfc2b8bf223d4e1829112aaafb7d8830ee90f875b6f17dd826
Unknown host QEMU_IFLA type: 50
Unknown host QEMU_IFLA type: 51
Unknown host QEMU_IFLA type: 47
Unknown host QEMU_IFLA type: 48
Unknown host QEMU_IFLA type: 43
Unknown host QEMU_IFLA type: 50
Unknown host QEMU_IFLA type: 51
Unknown host QEMU_IFLA type: 47
Unknown host QEMU_IFLA type: 48
Unknown host QEMU_IFLA type: 43
ERRO[0000] Parsing interface "eth0" failed: failed to acquire handle on network namespace: protocol family not supported 
WARN[0000] Got an error while trying to set up networking, but retrying: no active or valid interfaces available yet 
```

As I was fiddling with the docker networking, I thought it might have something to do with that, so I tried `0.4.2` but that worked.
```
# ./ignite-0.4.2 run weaveworks/ignite-ubuntu:latest -n yoINFO[0001] Created VM with ID "1d658f81761c7057" and name "yo" 
INFO[0001] Started Firecracker VM "1d658f81761c7057" in a container with ID "2b2c1a9a75a26da24d95ec169c23c8e94f8fca633b01c8afc4d6c8f15693f97e" 
# ./ignite-0.4.2 ps
VM ID                   IMAGE                           KERNEL                                  CREATED SIZE    CPUS    MEMORY          STATE   IPS             PORTS   NAME
1d658f81761c7057        weaveworks/ignite-ubuntu:latest weaveworks/ignite-kernel:4.19.47        17s ago 4.0 GB  1       512.0 MB        Running 172.17.0.2              yo
# ./ignite-0.4.2 rm yo
1d658f81761c7057 is running
# ./ignite-0.4.2 stop yo
# ./ignite-0.4.2 rm yo
INFO[0000] Removed VM with name "yo" and ID "1d658f81761c7057" 
# ./ignite-master run weaveworks/ignite-ubuntu:latest -n yo
INFO[0000] Created VM with ID "32305c5e1bd3735d" and name "yo" 
INFO[0001] Networking is handled by "docker-bridge"     
INFO[0001] Started Firecracker VM "32305c5e1bd3735d" in a container with ID "9e44e27f68929d67fc8fc9cac210567861f446c45c14d7282619a464c82fdb2c" 
```

v0.5.0 seems fine too
```
# ./ignite-0.5.0 run weaveworks/ignite-ubuntu:latest -n yo
INFO[0000] Created VM with ID "228875365a2ad090" and name "yo" 
INFO[0000] Pulling image "weaveworks/ignite:v0.5.0"...  
INFO[0009] Networking is handled by "docker-bridge"     
INFO[0009] Started Firecracker VM "228875365a2ad090" in a container with ID "690e2c671d36316c479071f9cc3d7d64bff44ba4b9be96084fcbfba415327662" 
```

**Comment by alex-leonhardt** [comment]
P.S. reason I wanted/needed master is to have the large image import fix - would be easiest if there was a _"quick"_ patch release maybe? :)

**Comment by twelho** [comment]
Could you run `ignite --log-level trace start 961caa578839a27c` and post the output of `docker logs`?
`Unknown host QEMU_IFLA type: 50` points to the ARM build, are you on x86 or ARM?

**Comment by twelho** [comment]
> P.S. reason I wanted/needed master is to have the large image import fix - would be easiest if there was a _"quick"_ patch release maybe? :)

We're planning to release `v0.5.1` with the image importing improvements this week (or early next week).

**Comment by alex-leonhardt** [comment]
I'm running on x86 ... I did see something ARM related when I ran `make` but thought it was just tagging the images 

here the output ```
# ./ignite-master  --log-level trace start yo
TRAC[0000] Client.Find; GVK: ignite.weave.works/__internal, Kind=VM
TRAC[0000] index: counted 0 VM object(s)
TRAC[0000] cache: miss when listing: ignite.weave.works/__internal, Kind=VM
TRAC[0000] cache: Get VM with UID "476d59b05ce03dad"
TRAC[0000] index: cache miss for VM with UID "476d59b05ce03dad"
TRAC[0000] index: storing VM object with UID "yo", meta: false
TRAC[0000] Client.Find; GVK: ignite.weave.works/__internal, Kind=Image
TRAC[0000] index: counted 0 Image object(s)
TRAC[0000] cache: miss when listing: ignite.weave.works/__internal, Kind=Image
TRAC[0000] cache: Get Image with UID "c42030942ae5998e"
TRAC[0000] index: cache miss for Image with UID "c42030942ae5998e"
TRAC[0000] index: storing Image object with UID "weaveworks/ignite-ubuntu:latest", meta: false
TRAC[0000] Client.Find; GVK: ignite.weave.works/__internal, Kind=Kernel
TRAC[0000] index: counted 0 Kernel object(s)
TRAC[0000] cache: miss when listing: ignite.weave.works/__internal, Kind=Kernel
TRAC[0000] cache: Get Kernel with UID "41470b9313b9e7d7"
TRAC[0000] index: cache miss for Kernel with UID "41470b9313b9e7d7"
TRAC[0000] index: storing Kernel object with UID "weaveworks/ignite-kernel:4.19.47", meta: false
INFO[0000] Networking is handled by "docker-bridge"
INFO[0000] Started Firecracker VM "476d59b05ce03dad" in a container with ID "abf3cfb4ffdafa6cfbbda2d20062e7fc4380b5758739a11e255d4add76bff89b"
FATA[0010] timeout waiting for ignite-spawn startup
# docker logs abf3cfb4ffdafa6cfbbda2d20062e7fc4380b5758739a11e255d4add76bff89b
Unknown host QEMU_IFLA type: 50
Unknown host QEMU_IFLA type: 51
Unknown host QEMU_IFLA type: 47
Unknown host QEMU_IFLA type: 48
Unknown host QEMU_IFLA type: 43
Unknown host QEMU_IFLA type: 50
Unknown host QEMU_IFLA type: 51
Unknown host QEMU_IFLA type: 47
Unknown host QEMU_IFLA type: 48
Unknown host QEMU_IFLA type: 43
ERRO[0000] Parsing interface "eth0" failed: failed to acquire handle on network namespace: protocol family not supported
WARN[0000] Got an error while trying to set up networking, but retrying: no active or valid interfaces available yet
```

a `0.5.1` release would be awesome :) 👍

**Comment by alex-leonhardt** [comment]
Oh I just saw this after doing another `make build-all`

```
docker tag weaveworks/ignite:v0.5.0-6-f351c694586c73-arm64 weaveworks/ignite:v0.5.0-6-f351c694586c73
```

**Comment by twelho** [comment]
Yes, that seems to be a bug from our side :sweat_smile: essentially the ARM build follows x86 and re-tags the image. Well spotted! For now as a workaround to only build for x86, run `make build-all-amd64`. I'll fix this ASAP.

**Comment by alex-leonhardt** [comment]
that's it, i re-tagged it and voila .. 

```
./ignite-master  --log-level trace start yo
TRAC[0000] Client.Find; GVK: ignite.weave.works/__internal, Kind=VM
TRAC[0000] index: counted 0 VM object(s)
TRAC[0000] cache: miss when listing: ignite.weave.works/__internal, Kind=VM
TRAC[0000] cache: Get VM with UID "476d59b05ce03dad"
TRAC[0000] index: cache miss for VM with UID "476d59b05ce03dad"
TRAC[0000] index: storing VM object with UID "yo", meta: false
TRAC[0000] Client.Find; GVK: ignite.weave.works/__internal, Kind=Kernel
TRAC[0000] index: counted 0 Kernel object(s)
TRAC[0000] cache: miss when listing: ignite.weave.works/__internal, Kind=Kernel
TRAC[0000] cache: Get Kernel with UID "41470b9313b9e7d7"
TRAC[0000] index: cache miss for Kernel with UID "41470b9313b9e7d7"
TRAC[0000] index: storing Kernel object with UID "weaveworks/ignite-kernel:4.19.47", meta: false
INFO[0000] Networking is handled by "docker-bridge"
INFO[0000] Started Firecracker VM "476d59b05ce03dad" in a container with ID "37faac0726cb2054e1a6157f386e9aa022231d1eb8af4b43c00316ba6dee30b6"
TRAC[0000] Client.Set; UID: "476d59b05ce03dad", GVK: ignite.weave.works/__internal, Kind=VM
TRAC[0000] cache: Set VM with UID "476d59b05ce03dad"
TRAC[0000] index: storing VM object with UID "yo", meta: false

# ./ignite-master ps
VM ID			IMAGE				KERNEL					SIZE	CPUS	MEMORY		CREATED		STATUS	IPS	PORTS	NAME
476d59b05ce03dad	weaveworks/ignite-ubuntu:latest	weaveworks/ignite-kernel:4.19.47	4.0 GB	1	512.0 MB	7m36s ago	Up 12s	172.17.0.2		yo
```
