### ISSUE TITLE
`weaveworks/ignite:<version>-arm64` images have `amd64` as their architecture

### ISSUE THREAD

**Issue by twelho** [weaveworks/ignite#345]
This doesn't affect `weaveworks/ignite:<version>` images, those are registered for both architectures. Just a nit, but would be good to fix at some point.

**Comment by stealthybox** [comment]
To clarify, our manifest list references the `-arm64` image properly, but the image itself has metadata for the wrong OS:
```
docker manifest inspect weaveworks/ignite:v0.6.2-arm64 -v
...
		"platform": {
			"architecture": "amd64",
			"os": "linux"
		}
```


We also have another subtle issue.
Our manifest list currently specifies:
```
docker buildx imagetools inspect weaveworks/ignite:v0.6.2
...
  Name:      docker.io/weaveworks/ignite:v0.6.2@sha256:c9b04a099a62fc44e3a26b4e098eabeb9dc34587205d3aa16e1cbc009f1a4f8b
  Platform:  linux/amd64
             
  Name:      docker.io/weaveworks/ignite:v0.6.2@sha256:41395728d971f2e46490393076e26b4f7351ed67a2e1b62cf2b2dd2b187664fc
  Platform:  linux/arm64
```

The second descriptor should probably also specify the arm64 variant:
ie: `linux/arm64/v8`

Compare `ubuntu:latest` with our `os/arch/variant`:
https://hub.docker.com/r/weaveworks/ignite/tags?page=1&name=v0.6.2
https://hub.docker.com/_/ubuntu?tab=tags&page=1&name=latest
