### ISSUE TITLE
After host reboots, ignite report VM up despite is not

### ISSUE THREAD

**Issue by aojea** [weaveworks/ignite#351]
I' ve just found this because when I tried to connect to the VM it failed after my server rebooted it wasn't there.

`ignite ps` reports is running bit is not, I guess has to be related to docker not restarting the container but couldn't dig further.

```sh
# sudo bin/ignite ssh my-vm
ssh: connect to host 172.17.0.11 port 22: No route to host
WARN[0001] SSH command terminated                       
# sudo bin/ignite ps
VM ID                   IMAGE                           KERNEL                                  SIZE    CPUS    MEMORY  CREATED STATUS          IPS         PORTS    NAME
e289e3b662dd7b71        weaveworks/ignite-ubuntu:latest weaveworks/ignite-kernel:4.19.47        4.0 GB  2       4.0 GB  13d ago Up <nil>        172.17.0.11 my-vm
# sudo bin/ignite rm my-vm
FATA[0000] e289e3b662dd7b71 is running                  
# sudo bin/ignite rm -f my-vm
FATA[0014] failed to kill container for VM "e289e3b662dd7b71": Error response from daemon: Cannot kill container: ignite-e289e3b662dd7b71: No such container: ignite-e289e3b662dd7b71 
# sudo bin/ignite ps
VM ID   IMAGE   KERNEL  SIZE    CPUS    MEMORY  CREATED STATUS  IPS     PORTS   NAME
```

**Comment by twelho** [comment]
Thanks for noticing, could you post the output of `sudo ignite inspect vm e289e3b662dd7b71 -oyaml`?

**Comment by aojea** [comment]
```
sudo bin/ignite inspect vm e289e3b662dd7b71 -oyaml
FATA[0000] can't find VM: no ID/name matches for "e289e3b662dd7b71" 
```

but I guess that's because if you see the snippet above the `rm -f` deletes the references

> # sudo bin/ignite rm my-vm
>FATA[0000] e289e3b662dd7b71 is running                  
># sudo bin/ignite rm -f my-vm
>FATA[0014] failed to kill container for VM "e289e3b662dd7b71": Error response from daemon: >Cannot kill container: ignite-e289e3b662dd7b71: No such container: ignite-e289e3b662dd7b71

in `kind` happens something similar because after rebooting the node the docker filtering still matches the containers tags, but the containers are not running

**Comment by aojea** [comment]
@twelho feel free to close it if you think is the expected behavior, just wanted to let you know

**Comment by twelho** [comment]
This is expected, as we don't support restarting VMs for now (including host restarts). The VM container doesn't persist and can't update the state after a sudden termination, resulting in the Ignite reporting the wrong state. Closing.
