### ISSUE TITLE
Remove v1alpha1 in v0.8.0

### ISSUE THREAD

**Issue by luxas** [weaveworks/ignite#355]
We will support upgrades so that you can seamlessly go one minor version up at any time without breaking, but we won't hold an old API version left in the binary more releases than necessary.

Upgrading from v1alpha1 (the only option in v0.4.0) to v1alpha2 was possible in v0.5.0, but is not needed in v0.6.0 anymore as everything touched by v0.5.0 is always at v1alpha2.

**Update:** We'll remove `v1alpha1` from v0.7.0, as that most likely introduces `v1alpha3`. Maintaining three API versions in parallel would take up too much time/effort. v0.6.0 will thus have `v1alpha1` still available (use discouraged).

**Comment by luxas** [comment]
@chanwit

**Comment by chanwit** [comment]
got it!

**Comment by luxas** [comment]
@darkowlzz could you please do this? when this is done, we can create a new `v1alpha3`, to which you can add the Config object, ref: #601

**Comment by darkowlzz** [comment]
@luxas sure. Is it just removing the package `pkg/apis/ignite/v1alpha1` and updating any code that uses it to `v1alpha2`?

**Comment by luxas** [comment]
Yes. After that we can duplicate v1alpha2 into v1alpha3, and then start modifying v1alpha3 to have the new things we want.
