### ISSUE TITLE
old docker version

### ISSUE THREAD

**Issue by kobayashi** [weaveworks/ignite#358]
From [Installing dependencies](https://ignite.readthedocs.io/en/stable/installation.html#installing-dependencies), is there any reason for using older version of docker package (not docker-ce)?

**Comment by twelho** [comment]
Hi @kobayashi! :wave: 
No particular reason, other than `docker.io` being readily available in Ubuntu without the need to add external PPAs. Feel free to use `docker-ce`, it should work just fine.

**Comment by kobayashi** [comment]
Hello @twelho,

Thank you for letting me know. Do I have a chance to PR the docs about this?
Something like this.
```
ignite does not depend on docker package version. If you already installed docker-ce, you don't need to replace it to docker.io.
```

**Comment by twelho** [comment]
Yes absolutely, go ahead :+1:

**Comment by kobayashi** [comment]
PR was merged. Close
