### ISSUE TITLE
Ignite(-spawn) leaks device mapper devices

### ISSUE THREAD

**Issue by twelho** [weaveworks/ignite#365]
It seems like the `device mapper` snapshot cleanup has stopped working at some point (again), it might be a specific command (I suspect `rm -f`) that is causing a leak of dm and loop devices. Noticed after using `Footloose` to repeatedly spin up and tear down a cluster of VMs.

**Comment by twelho** [comment]
`rm -f` works properly, the issue is improper/non-working cleanup if `run` or `start` fail during the call e.g. if any of the OCI images could not be pulled.

**Comment by chanwit** [comment]
addressed in #381

**Comment by chanwit** [comment]
Steps to reproduce In my scenario:

Scenario 1:
I got a new binary compiled with different ignite version say, `0.6.0+1-dirty`.
When running `ignite run` it's going to pull `weaveworks/ignite:0.6.0+1-dirty` which does not exist. Then the VM creation failed.

After that `sudo ignite rm -f <vm_id>`

Then `sudo dmsetup ls`, the dm devices still left on disk.

**Comment by chanwit** [comment]
ping @stealthybox could you please close this one. thank you.

**Comment by chanwit** [comment]
This issue could be closed for now. I'll re-open it if things still wrong.
