### ISSUE TITLE
Not able to run make build-all 

### ISSUE THREAD

**Issue by karanparhar** [weaveworks/ignite#383]
Error : Makefile:20: *** missing separator.  Stop

**Comment by chanwit** [comment]
from which branch you're building?

if from the master, it's just working fine to me.

**Comment by karanparhar** [comment]
I'm building from master (and v0.6.0)

**Comment by chanwit** [comment]
It might be relating to tab characters in `Makefile` getting changed or replaced.
Did you modify the `Makefile`?

**Comment by silenceshell** [comment]
I have met this problem on macOS, for my make is `GNU Make 3.81`, which does not support `undefine`.

To avoid this, just delete the line 20, or upgrade your make above version 3.82.

`undefine GOFLAGS`

**Comment by chanwit** [comment]
that surprised me! Thank you @silenceshell .
I'm using Linux so I haven't noticed that a different version of `make` on macOS would cause a problem to @karanparhar .

**Comment by chanwit** [comment]
To help confirm this, my `make` version is 4.` and I don't have the problem with `undefine`.

**Comment by chanwit** [comment]
noted that we need to specify the minimum version of `make` somewhere in the build doc.

**Comment by silenceshell** [comment]
@chanwit I agree and would like to submit a PR to fix the doc :)

**Comment by karanparhar** [comment]
@chanwit After updating the make version i'm able to  build

**Comment by chanwit** [comment]
@silenceshell sure please do.

**Comment by chanwit** [comment]
@karanparhar great to hear that it's working for you.
