### ISSUE TITLE
Keep docker as the default runtime for a while

### ISSUE THREAD

**Issue by chanwit** [weaveworks/ignite#390]

**Comment by stealthybox** [comment]
+1
The containerd version we depend on is too new for most users.
We also have no version gate/pre-flightcheck which means users will receive this error:
```shell
sudo ./ignite run weaveworks/ignite-ubuntu --runtime containerd
INFO[0000] Created VM with ID "f639aa74f3e7ff03" and name "purple-night" 
FATA[0000] failed to start container for VM "f639aa74f3e7ff03": runtime "io.containerd.runc.v1" binary not installed "containerd-shim-runc-v1": file does not exist: unknown 
```

**Comment by luxas** [comment]
What containerd version do you use? The v1 shim is available at least in v1.2, maybe v1.1 too

**Comment by luxas** [comment]
> We also have no version gate/pre-flightcheck which means users will receive this error

Preflight checks will be added here: https://github.com/weaveworks/ignite/pull/360
Just add a containerd check in there later to check for containerd v1.1+ or v1.2+, whatever is needed

**Comment by chanwit** [comment]
Currently the containerd cli uses 1.3.0-beta.2 (also about to upgrade to 1.3.0-rc.0).
Feedback from a user from slack saying that he already has `docker` and why does he still need to install `containerd`.
So we plan to provide auto-detection as a workaround.

Until we could also ship a certain version of containerd to provider better UX out-of-the-box, I suggest we keep docker runtime for a time being.

**Comment by stealthybox** [comment]
> What containerd version do you use? The v1 shim is available at least in v1.2, maybe v1.1 too

@luxas newest docker-ce on ubuntu uses containerd 1.2.6:
```bash
docker version                                                                                                                                                          19/09/6 10:13:40 am
Client: Docker Engine - Community
 Version:           19.03.2
 API version:       1.40
 Go version:        go1.12.8
 Git commit:        6a30dfca03
 Built:             Thu Aug 29 05:29:17 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.2
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.8
  Git commit:       6a30dfca03
  Built:            Thu Aug 29 05:27:52 2019
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.2.6
  GitCommit:        894b81a4b802e4eb2a91d1ce216b8817763c29fb
 runc:
  Version:          1.0.0-rc8
  GitCommit:        425e105d5a03fabd737a126ad93d62a9eeede87f
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

This is before the shim had multiple versions:
```bash
sudo ls /usr/bin/containerd-shim*
/usr/bin/containerd-shim
```

**Comment by stealthybox** [comment]
Related user issue in slack: https://weave-community.slack.com/archives/CL1A4S5UJ/p1567752222028300

**Comment by stealthybox** [comment]
#411 removes the need to rollback to docker as the default since it should now enable use of the Legacy Linux Runtime available with all modern versions of docker.
