### ISSUE TITLE
Cant pull Docker hello-world image

### ISSUE THREAD

**Issue by Strum355** [weaveworks/ignite#402]
![image](https://user-images.githubusercontent.com/18282288/64364343-87511880-d00a-11e9-8c96-c1fe947eac85.png)

**Comment by stealthybox** [comment]
Thanks for reporting -- I can reproduce this on master:
```
sudo bin/ignite image import hello-world
INFO[0000] Docker image "hello-world:latest" not found locally, pulling... 
INFO[0001] Starting image import...                     
FATA[0001] failed to format image 8b8e8bc523a3065f: command ["mkfs.ext4" "-b" "4096" "-I" "256" "-F" "-E" "lazy_itable_init=0,lazy_journal_init=0" "/var/lib/firecracker/image/8b8e8bc523a3065f/image.ext4"] exited with "mke2fs 1.44.6 (5-Mar-2019)\n/var/lib/firecracker/image/8b8e8bc523a3065f/image.ext4: Not enough space to build proposed filesystem while setting up superblock\n": exit status 1 
```
With `golang:latest` (which is significantly larger), there's no issue:
```
sudo bin/ignite image import golang
INFO[0000] Docker image "golang:latest" not found locally, pulling... 
INFO[0138] Starting image import...                     
INFO[0141] Imported OCI image "golang:latest" (778.2 MB) to base image with UID "cf32284d89a33432" 
INFO[0141] Created image with ID "cf32284d89a33432" and name "golang:latest" 
```

**Comment by uLan08** [comment]
I'd like to work on this.

**Comment by chanwit** [comment]
sure @uLan08

**Comment by uLan08** [comment]
Any tips on where to start looking?

**Comment by darkowlzz** [comment]
Hi, I got curious about this issue, debugged and found a few problems that are related to tiny images and the images made from scratch.
When a very small image is imported, the filesystem file (in `/var/lib/firecracker/image/`) that's created based on the image source size is also small. In case of `hello-world` image, it's so small that mkfs that's run on the filesystem file fails with the following error:
```
FATA[0000] failed to format image 0f58e80dcf4bae0f: command ["mkfs.ext4" "-b" "4096" "-I" "256" "-F" "-E" "lazy_itable_init=0,lazy_journal_init=0" "/var/lib/firecracker/image/0f58e80dcf4bae0f/image.ext4"] exited with "mke2fs 1.45.3 (14-Jul-2019)\n/var/lib/firecracker/image/0f58e80dcf4bae0f/image.ext4: Not enough space to build proposed filesystem while setting up superblock\n": exit status 1 
```
Even through the file is created to be 3x of the image size, refer https://github.com/weaveworks/ignite/blob/v0.6.3/pkg/dmlegacy/image_format.go#L37, it seems to not be enough.
Maybe adding a minimum size check for image file would be a good solution. When an image source is smaller than the image size, use the minimum file size.

Once the filesystem size issue is resolved, the image import fails with the following error:
```
DEBU[0000] Copying in files to the image file from a source... 
FATA[0000] symlink ../proc/net/pnp /tmp/562398507/etc/resolv.conf: no such file or directory 
```
After trying a few other images, it looks like this happens for small images that are created from `scratch` only, `hello-world`, `alpine`, `busybox`, etc.
Failing to create resolv.conf results in network issues in the VM.
I'm not sure about a solution for this. Maybe just log a warning when resolv.conf setup fails?
