### ISSUE TITLE
ignite shouldn't ask for root permissions just to display its version

### ISSUE THREAD

**Issue by dlespiau** [weaveworks/ignite#406]
While https://github.com/weaveworks/ignite/issues/24 captures things required to not run as root, the `version` command shouldn't require to be run as root:

```console
$ ignite version -o short
FATA[0000] This program needs to run as root.           
```

**Comment by chanwit** [comment]
Agree.

Thank you for reporting. I'm working on it.

**Comment by stealthybox** [comment]
Determining what the more specific permissions are and how to check for them would be a more appropriate set of pre-flight checks than just gating on UID==0.

**Comment by chanwit** [comment]
Currently it's globally checked for root UID at the root command. That's why even with `ignite version` does need root.

**Comment by Khalian** [comment]
This is not fixed

ignite version

```
ignite version
Ignite version: version.Info{Major:"0", Minor:"7", GitVersion:"v0.7.1", GitCommit:"e80a75a4a451395deeb03e37dde7057b9fc29606", GitTreeState:"clean", BuildDate:"2020-07-13T15:52:07Z", GoVersion:"go1.14.2", Compiler:"gc", Platform:"linux/amd64", SandboxImage:version.Image{Name:"weaveworks/ignite", Tag:"v0.7.1", Delimeter:":"}, KernelImage:version.Image{Name:"weaveworks/ignite-kernel", Tag:"4.19.125", Delimeter:":"}}
Firecracker version: v0.21.1
Runtime: containerd
```
and usage.

```
ignite ps
FATA[0000] This program needs to run as root.
```
0.7.1 is the latest version as per the releases page.
