### ISSUE TITLE
zombie VM that can't be stopped or removed unless forced

### ISSUE THREAD

**Issue by dimitropoulos** [weaveworks/ignite#407]
Love this project!  Thanks for working on it!

The issue I'm hitting is that I have a stuck VM that I couldn't seem to remove:

![Screenshot_20190906_075253](https://user-images.githubusercontent.com/15232461/64437099-a34ccc80-d093-11e9-8546-07fb535dcc9b.png)

I really wish I could provide more context as to how this happened but it was during a debugging session (of a different problem) where I was trying many many things, and it was only later that I realized there was an extra VM that wouldn't go away.

I see that https://github.com/weaveworks/ignite/issues/159 has been closed, so I thought it best to report that this is happening as of `v0.5.2`.

Thankfully I _was_ able to remove it with `sudo ignite rm --force`, but it took me some time to realize that was even an option.  Perhaps if nothing else, we can add something to the docs to help out in this case?  Hopefully such a thing isn't already documented and I missed it.

**Comment by chanwit** [comment]
Thank you for your kind words :-)

>  Perhaps if nothing else, we can add something to the docs to help out in this case?

Yes sure. Would you like to contribute the docs saying this?
