### ISSUE TITLE
Copy files from host to VM, while the VM is in running state

### ISSUE THREAD

**Issue by YachikaRalhan** [weaveworks/ignite#419]
Not able to copy while VM is running.
There is `--copy-files` flag, but only works with ignite run command

**Comment by yachika49** [comment]
Not able to copy while VM is running.
There is --copy-files flag, but only works with ignite run command

**Comment by chanwit** [comment]
Thank you for reporting this @yachika49 !

Maybe this would be implemented as `ignite cp` sub command, and using `scp` underneath.

**Comment by chanwit** [comment]
/affect pre-flight check for the `scp` binary.

**Comment by gpauloski** [comment]
@chanwit I would like to work on this.
