### ISSUE TITLE
CNI setup appears more latent than docker-bridge

### ISSUE THREAD

**Issue by stealthybox** [weaveworks/ignite#423]
Network connectivity does not require sleeps for `docker+docker-bridge` when performing run, then exec.

`docker+cni` only succeeds locally on my laptop with sleep values >= 2 seconds.

Described in #422 with reproducing tests.

**Comment by chanwit** [comment]
Adding DNS 8.8.8.8 and 8.8.4.4 directly thru --dns (a pending PR) eliminated this wait. 
I'm guessing that what's happening on my machine was probably some services trying to query DNS and failed by timeout. 

The workaround is just adding Ignite to wait for the SSH service to start. So we can make sure that the subsequent commands could be able to `ssh`, and `exec` thru the SSH port.

**Comment by chanwit** [comment]
@stealthybox If you're OK, I think we could postpone this one to the next release?
If so, we could cut release by Monday and do integration test with other projects (which is higher priority).
