### ISSUE TITLE
Ignite vm stop/rm - iptables: Too many links

### ISSUE THREAD

**Issue by lucidprogrammer** [weaveworks/ignite#462]
This issue is not in the commit. 4966569dfa77d653beef9bb552785183f41fe001

Ignite version: version.Info{Major:"0", Minor:"6+", GitVersion:"v0.6.0-84+292dd05b1b9389", GitCommit:"292dd05b1b938928d735c9977ac7ae48097b4d2b", GitTreeState:"clean", BuildDate:"2019-09-27T10:07:45Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
Firecracker version: v0.18.0
Runtime: containerd

```
INFO[0000] Removing the container with ID "ignite-bc6b53e9addd1040" from the "cni" network 
FATA[0000] running [/sbin/iptables -t nat -X CNI-598ec25f80183838805ef182 --wait]: exit status 1: iptables: Too many links.
```

If I look at iptables, it removes only the MASQUERADE and ACCEPT. POSTROUTING remains and the main nat entry.

**Comment by chanwit** [comment]
Thank you @lucidprogrammer for reporting!!

It seems being addressed by https://github.com/weaveworks/ignite/pull/461 ? cc @stealthybox 

@lucidprogrammer If you think it's a new bug, could you please provide us steps to reproduce.
I'm guessing you're creating massive number of VMs?

**Comment by lucidprogrammer** [comment]
> Thank you @lucidprogrammer for reporting!!
> 
> It seems being addressed by #461 ? cc @stealthybox
yes it seems the same issue. 
> @lucidprogrammer If you think it's a new bug, could you please provide us steps to reproduce.
> I'm guessing you're creating massive number of VMs?
thats the idea!! :-)

**Comment by stealthybox** [comment]
@lucidprogrammer, I was seeing this before I wrote #461 -- it happens when CNI is instructed to remove rules for a cni network name that does not exist. (the comment that's used to match is incorrect)

Can you try it out a new build and check if you're still having this problem?

**Comment by lucidprogrammer** [comment]
@stealthybox current commit 03baaa9c8152f4ae464f950bcbfef09c55c9ffae works fine.
It will be ideal if the ip address in /var/lib/cni/networks/ignite-cni-bridge/last_reserved_ip.0 is rolled back when a vm is removed or stopped.
