### ISSUE TITLE
prometheus socket left open after ignited gitops terminates 

### ISSUE THREAD

**Issue by palemtnrider** [weaveworks/ignite#485]
While running `ignited gitops` a prometheus socket is opened but not closed on termination.  This causes errors on subsequent runs if the user doesn't remove the /var/lib/firecracker/daemon.sock file.

>Ignite version: version.Info{Major:"0", Minor:"6+", GitVersion:"v0.6.0-106+0a90cfbced8163-dirty", GitCommit:"0a90cfbced8163507831f885d3eef343e20f0875", GitTreeState:"dirty", BuildDate:"2019-11-04T04:05:01Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}
Firecracker version: v0.18.0
Runtime: containerd

**Comment by bbros-dev** [comment]
@chanwit and @palemtnrider I'm still seeing this behavior:

System `vagrant@service-ubuntu-1804`
```bash
$ sudo ignited version
Ignite version: version.Info{Major:"0", Minor:"6", GitVersion:"v0.6.3", GitCommit:"ed51b9378f6e0982461074734beb145d571d56a6", GitTreeState:"clean", 
BuildDate:"2019-12-10T06:20:00Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}
Firecracker version: v0.18.1
Runtime: containerd
```

```bash
$ sudo ignited daemon
INFO[0000] Starting reconciliation loop... 
^CClosing...
$ sudo ignited daemon
INFO[0000] Starting reconciliation loop...              
ERRO[0000] prometheus server was stopped with error: listen unix /var/lib/firecracker/daemon.sock: bind: address already in use 
^CClosing...
```

**Comment by chanwit** [comment]
Acked. Thank you @bbros-dev for reporting!

**Comment by bbros-dev** [comment]
Can you please re-open this so status can be tracked?

**Comment by bbros-dev** [comment]
bump @chanwit - is there a reason this shouldn't be reopened?
