### ISSUE TITLE
make tidy should run in a container by default

### ISSUE THREAD

**Issue by teaguecole** [weaveworks/ignite#489]
`make tidy` currently runs directly on your host relying on the tools and their respective versions.  While there is `make tidy-in-docker`, it is not documented.  Let's either replace `make tidy` in the documentation with `make-tidy-docker` or change the functionality of `make tidy` to be  containerized.

**Comment by mprey** [comment]
Hello, I can tackle this issue for you. Did you decide whether you wanted to replace make tidy in the documentation or the functionality?

**Comment by teaguecole** [comment]
Hey @mprey glad to see you are interested. I am a newbie here but I will try to help. Let me bring in @stealthybox as he has more expertise about this.  What I would say is that from what I understand, what the typical contributor will actually want to do is `tidy-in-docker` but the docs don't match.  So the easier route would be to understand the functionality of tidy and tidy-in-docker  and correct the documentation to use tidy-in-docker.  The other route would be to determine if we need both tidy and tidy-in-docker and if we can consolidate.  That is where I would want @stealthybox reccomendation.

**Comment by teaguecole** [comment]
Also apologies for not getting back to you until 4 days later!!!  Got caught up with other work stuff etc. you know! :)

**Comment by AydamiroV** [comment]
Hey @teaguecole! I am in the group with @mprey. I am trying to start on the issue, however, I am not quite sure where to start from. Could you, please, give me some hints? Thanks!

**Comment by kobayashi** [comment]
`make autogen tidy` command [described in docs](https://github.com/weaveworks/ignite/blob/master/CONTRIBUTING.md#contributing-your-code) seems to call `tidy` in both docker and local, right? `autogen` run `tidy` inside a container then,`tidy` is called in local.
If this is collect, just running `make autogen` is fine for `tidy` in docker container. Then, we can remove `tidy-in-docker`.
I would like to go further if my thought and steps are ok.

**Comment by stealthybox** [comment]
@kobayashi, it's true that the `autogen` normally runs in a container (overrideable via `GO_MAKE_TARGET`).

However, a dev may not want to run `autogen` every time they needed to `tidy-in-docker`.

Unfortunately, `tidy`'s interaction with `go mod` as we've upgraded through different go versions has given us different results in and out of the container and has been the source of broken CI and builds.

**Comment by araman18** [comment]
Hello, I am a student from the University Of Texas At Austin and as a part of my virtualization class assignment I wanted to ask if I would be allowed to work on this issue, I was wondering if I could be assigned to this issue. Thanks.
