### ISSUE TITLE
Documentation: Fix kernel module loop check instruction

### ISSUE THREAD

**Issue by bbros-dev** [weaveworks/ignite#534]
In [Host requirements](https://ignite.readthedocs.io/en/stable/dependencies.html#host-requirements)

Clarify the loop module must be built in and not loaded.  As the documentation stands, on Ubuntu 18.04, the documented command `modprobe -v loop` returns nothing.

Suggestion:

Verify `loop` module is built into your kernel:

```bash
# grep 'loop' /lib/modules/`uname -r`/modules.builtin
kernel/drivers/block/loop.ko
```

**Comment by stealthybox** [comment]
Thanks

**Comment by bbros-dev** [comment]
In getting Debian-10 to pass the integration tests we noticed that the `modprobe -v loop` fell silent after the first use.  It seems a robust approach is `lsmod | grep loop` for kernel modules not built in.
