### ISSUE TITLE
`ignite vm rm <uid>` reports success, but VM is not removed.

### ISSUE THREAD

**Issue by bbros-dev** [weaveworks/ignite#547]
From the `**....**` below you'll notice the VM is not removed:

`sudo ignite vm rm <uid>` reports success, twice, but VM is not removed.

```bash
$ sudo ignite vm rm abcd567891234567
INFO[0000] Removed VM with name "smoke-test" and ID "abcd567891234567"
$ sudo ignite vm rm abcd567891234567
INFO[0000] Removed VM with name "smoke-test" and ID "abcd567891234567"
$ sudo ignite vm 
VM ID                   IMAGE                           KERNEL                                  SIZE    CPUS    MEMORY     C
REATED          STATUS  IPS     PORTS   NAME
1234567891234567        weaveworks/ignite-ubuntu:latest weaveworks/ignite-kernel:4.19.47        1.2 GB  1       456.0 MB   3
d6h ago Stopped                 smoke-test
**abcd567891234567**        weaveworks/ignite-ubuntu:latest weaveworks/ignite-kernel:4.19.47        1.2 GB  1       456.0 MB   3
d5h ago Stopped                 smoke-test
```

**Comment by darkowlzz** [comment]
Hi, thanks for reporting this. Do you have steps to reproduce this issue? More info about your ignite setup would be useful.
It looks like your VMs were in stopped state before you tried to delete them. Maybe something went wrong while stopping the VMs?
Passing `--log-level debug` in the commands can give some more detail about what's going.

**Comment by darkowlzz** [comment]
Also, I noticed that the VMs have the same name. How did you create them?

**Comment by bbros-dev** [comment]
From memory.... the VM's were created by editing the manifest file in `/etc/firecracker/manifests`.
This was around the time:

1. the `ignited` installation was incomplete because it did not have docker installed - trying to keep that off our systems, but it seems the ignite is not usable without it. For the moment.
1. The manifests were, following the documenttaion, in YAML. But then I switched to JSON as discussed in some other issue.

Let me know if you want more information.

**Comment by bbros-dev** [comment]
Closing.  Following a review, we will not be using ignite outside of developer personal workflows, so won't be able to devote any time to issues outside of that scope.
