### ISSUE TITLE
StartVM hardcoded to weavworks/ignite:<tag>

### ISSUE THREAD

**Issue by alex-leonhardt** [weaveworks/ignite#566]
Hi,

I tried to manually build ignite and that worked just fine, however, when trying to run the new binary (on a different host), it attempted to download a `weaveworks/ignite` image that won't exist .. I tracked it down to this: https://github.com/weaveworks/ignite/blob/master/pkg/operations/start.go#L41 

Would it be feasible to allow this to use the `DOCKER_USER` from the Makefile https://github.com/weaveworks/ignite/blob/master/Makefile#L35 ? 

So that it would not attempt to use a `weaveworks/ignite:<does-not-exist>` container when spinning up the VM ?

Thanks
Alex

**Comment by stealthybox** [comment]
Hi @alex-leonhardt, this is now configurable at runtime via flags and VM API Spec configs.

Fixed by #598 released in v0.7.0
