### ISSUE TITLE
Documentation for apiVersion is inconsistent

### ISSUE THREAD

**Issue by morancj** [weaveworks/ignite#627]
The example in https://github.com/weaveworks/ignite/blob/master/docs/installation.md#ignited-daemon uses `apiVersion: ignite.weave.works/v1alpha3`, while the example in readthedocs [Run Ignite VMs declaratively](https://ignite.readthedocs.io/en/stable/declarative-config/) uses `apiVersion: ignite.weave.works/v1alpha2`.

**Comment by darkowlzz** [comment]
Hi, thanks for going through the docs. We added v1alpha3 API recently, after v0.7.0 release. The docs at https://ignite.readthedocs.io/en/stable/declarative-config/ are of the stable release. The latest, unreleased docs have the new API https://ignite.readthedocs.io/en/latest/declarative-config/ .
Hope that clears the confusion.

**Comment by morancj** [comment]
Understood, thanks!
