### ISSUE TITLE
AMI from ignite vm?

### ISSUE THREAD

**Issue by lukemarsden** [weaveworks/ignite#629]
Hey folks, awesome project!

How hard would it be to create an AMI from an ignite VM? (more specifically, from the docker image that is used to spawn ignite VMs)

The use case is that VM images can be created in dev- and test-friendly ignite world, and then spun into fully fledged EC2 instances for production (managed by terraform).

**Comment by morancj** [comment]
Hi @lukemarsden,
I know this doesn't answer your question, but have you considered [HashiCorp Packer](https://www.packer.io/) as a workaround?

**Comment by lukemarsden** [comment]
Sure, that makes sense. Closing this. Thanks!
