### ISSUE TITLE
Logging everywhere

### ISSUE THREAD

**Issue by twelho** [weaveworks/ignite#63]
- [x] `errutils` removed

**Comment by luxas** [comment]
Part of this is done, part of this is for later

**Comment by luxas** [comment]
Now that we have structured logging in v0.4.0, there are a couple of TODOs still:

 - Start using logrus everywhere; add log statements for different levels all over the applications
 - Get rid of `errutils.Check`
 - Pass loglevel through from `ignite` to `ignite-spawn` and Firecracker itself.
