### ISSUE TITLE
v1alpha3 commit breaks existing install

### ISSUE THREAD

**Issue by stealthybox** [weaveworks/ignite#649]
I noticed recent builds are not working on my Ubuntu 20 dev machine and a bisect found d44db2f65 to be the problem:
```shell
git bisect start master v0.7.0
git bisect run bash -c "make ignite bin/amd64/Dockerfile &>/dev/null && sudo bin/ignite run weaveworks/ignite-ubuntu"
```
```
d44db2f65a2cf43903f7caf02d33ba39cc866826 is the first bad commit
commit d44db2f65a2cf43903f7caf02d33ba39cc866826
Author: Sunny <darkowlzz@protonmail.com>
Date:   Fri Jun 19 21:35:33 2020 +0530

    Add ignite/v1alpha3 API

    Generated by copying v1alpha2 into v1alpha3 and running `make autogen`.
```

Looks like something we added with the new API machinery may not be forward compatible with existing installs.

**Comment by darkowlzz** [comment]
Hi, I tried this on a new machine, cloned the repo, checked out to tag v0.7.0 and ran `make`, create a VM, deleted it. And then I checked out to the latest and ran `make` again, created a VM, and everything seemed fine.
As per the commands pasted above, it looks like only the ignite binary is being build again, not ignite-spawn. While adding the new API, I remember I had to rebuild ignite-spawn as well.
I tried the above again, checked out v0.7.0, ran `make`. Checked out to the latest, ran only `make ignite bin/amd64/Dockerfile`, and then created a VM, and got an ignite spawn failure:

```console
INFO[0000] Created VM with ID "fa65a12e1105d7f4" and name "my-vm"
INFO[0001] Networking is handled by "cni"
INFO[0001] Started Firecracker VM "fa65a12e1105d7f4" in a container with ID "ignite-fa65a12e1105d7f4"
FATA[0011] timeout waiting for ignite-spawn startup
```

Running `make ignite-spawn bin/amd64/Dockerfile` and trying again fixed the issue.

Did you get the same failure when you tried?

**Comment by twelho** [comment]
I ran the following bisect successfully:
```
git bisect start master v0.7.0
git bisect run bash -c "make ignite ignite-spawn &>/dev/null && sudo bin/ignite run weaveworks/ignite-ubuntu"
```
So I think even though you updated the ignite-spawn image with `bin/amd64/Dockerfile` (which also exports it to containerd), using that target doesn't actually _build_ the ignite-spawn binary. So you are just repackaging the ignite-spawn you had on your system for each bisect. @stealthybox

**Comment by stealthybox** [comment]
Thanks for calling that out.
I haven't reproduced it, on this commit range, but I noticed this issue with my make target when working on the udev ignite-spawn changes yesterday.
I'm pretty sure that's the issue

The arch specific target I changed to is:
`make bin/amd64/{ignite,ignite-spawn,Dockerfile}`
