### ISSUE TITLE
Consider adding `ignite exec [vm] [command]`

### ISSUE THREAD

**Issue by luxas** [weaveworks/ignite#65]
It would:
a) use ssh internally
b) require a command, unlike `ssh`

Don't know if we want to do this or not

**Comment by BenTheElder** [comment]
This would be pretty useful for my use cases, especially if it preserved the exit code :-)

I took a quick look, this seems doable, any thoughts on why we might not want this?

**Comment by luxas** [comment]
Ok, great!
Let's add it to the v0.5.0 milestone.
Can you help out with making it happen?

**Comment by BenTheElder** [comment]
Yes, I think I can help with this!

Side note: WDYT about https://godoc.org/golang.org/x/crypto/ssh ? I'm pretty sure go has decent SSH clients that we could use to avoid manipulating the host machine's known hosts etc. EG https://godoc.org/golang.org/x/crypto/ssh#Dial

**Comment by luxas** [comment]
> Yes, I think I can help with this!

Wonderful, thank you!

> Side note: WDYT about https://godoc.org/golang.org/x/crypto/ssh ? I'm pretty sure go has decent SSH clients that we could use to avoid manipulating the host machine's known hosts etc. EG https://godoc.org/golang.org/x/crypto/ssh#Dial

Thanks for the pointer! I've never used it (yet!), but would be happy to do so. Exec'ing out to `ssh` was just the fastest way to implement this :)
I'll add this to #150
