### ISSUE TITLE
TODO Fix `ignite stop --runtime=docker` related CI test failure

### ISSUE THREAD

**Issue by stealthybox** [weaveworks/ignite#658]
See the commented out `TestVolumeWithDockerAndDockerBridge` from #653 for the unrelated test failure.

@darkowlzz mentions that this test passes on his digital ocean machine.
One guess is that this failure is timing or race related.
We suppose that this could be resolved in the docker runtime client.

**Comment by bboreham** [comment]
Isn't this the same problem as in #679 ?

**Comment by darkowlzz** [comment]
> Isn't this the same problem as in #679 ?

Yes, they are all docker related with the same container stop issue. The fix in #773 should solve this.
Great job on that 🥇

**Comment by darkowlzz** [comment]
> did #773 solve this?

Yes, that solved the issue and since then we have been running `TestVolumeWithDockerAndDockerBridge` test without any issue.
Closing this issue. Feel free to ask any related questions if you have any. Thanks :)
