### ISSUE TITLE
Installation instructions dont work for Amazon Linux 2 for docker ce

### ISSUE THREAD

**Issue by Khalian** [weaveworks/ignite#670]
I created an EC2 instance with an Amazon Linux 2 AMI on a r5.metal instance since I dont have a box lying around with kvm and VT-x virt lying around. 

I was looking at the instructions for installing the pre reqs here. 

https://github.com/weaveworks/ignite/blob/master/docs/installation.md

Now there are no instructions for installing ignite on Amazon Linux (or RHEL for that matter) so I tried the centos one, since that is the closest.

On top of messing up the instructions with sudo, I ran

```
which containerd || ( yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo && yum install -y containerd.io )
```

I got the error on the last command

```
[ec2-user@ip-172-31-10-187 ~]$ sudo yum install -y containerd.io
Loaded plugins: extras_suggestions, langpacks, priorities, update-motd
docker-ce-stable                                                                                      | 3.5 kB  00:00:00
(1/2): docker-ce-stable/x86_64/updateinfo                                                             |   55 B  00:00:00
(2/2): docker-ce-stable/x86_64/primary_db                                                             |  45 kB  00:00:00
Resolving Dependencies
--> Running transaction check
---> Package containerd.io.x86_64 0:1.2.13-3.2.el7 will be installed
--> Processing Dependency: container-selinux >= 2:2.74 for package: containerd.io-1.2.13-3.2.el7.x86_64
--> Finished Dependency Resolution
Error: Package: containerd.io-1.2.13-3.2.el7.x86_64 (docker-ce-stable)
           Requires: container-selinux >= 2:2.74
 You could try using --skip-broken to work around the problem
 You could try running: rpm -Va --nofiles --nodigest
```

Now I could go and start hunting for how to install containerd in AL2, but I expect a company like weaveworks to have a more elaborate set of instructions for installation, including reliable reproducible ways to install even the pre reqs.

**Comment by Khalian** [comment]
This should cover it : https://github.com/weaveworks/ignite/pull/671

**Comment by stealthybox** [comment]
Sorry -- I missed this issue when reading your PR.
It looks like this require is failing:
```
Requires: container-selinux >= 2:2.74
```

Here's the fix, I'll update the PR suggestion
https://github.com/aws/containers-roadmap/issues/614#issuecomment-559619366
