### ISSUE TITLE
Integrate Ignite with Footloose

### ISSUE THREAD

**Issue by luxas** [weaveworks/ignite#75]
Footloose currently supports "booting VMs" in docker containers, just running `/sbin/init` in a slightly modified container. We should create the integrations in Footloose to allow spinning up real VMs with Ignite as an option instead.

Most of this code is already created in my fork here, just need to formalize it: https://github.com/luxas/footloose/tree/ignite_v2, and do a new Footloose release.

**Comment by luxas** [comment]
@robertojrojas will work on this :clap:

**Comment by luxas** [comment]
This work is happening in https://github.com/weaveworks/footloose/pull/178

**Comment by luxas** [comment]
https://github.com/weaveworks/footloose/pull/178 is merged; awesome! Now, let's get to a place were we have a released version of Footloose that plays well with the latest Ignite version, and create some docs.

cc @robertorojas @dlespiau

**Comment by robertojrojas** [comment]
Thanks @luxas I have another PR in the works that I'll be submitting soon. I'll be more than happy to help in anything I can.

**Comment by luxas** [comment]
@robertojrojas could you add some docs about how to use footloose with ignite in this repo in `docs/` please?

**Comment by robertojrojas** [comment]
@luxas sure, I'll work on that and submit a PR.
