### ISSUE TITLE
Add support for adding volumes to `ignite run`

### ISSUE THREAD

**Issue by luxas** [weaveworks/ignite#76]
Firecracker supports attaching any block device to `/dev/vdX` in the VM.
We should integrate with CSI (https://github.com/container-storage-interface/spec) or similar software to easily expose attaching additional storage to VMs for persistence (we should also document that we shall treat each VM as ephemeral more or less)

**Comment by pditommaso** [comment]
I would love to see host volume mounts à la Docker.

**Comment by luxas** [comment]
> I would love to see host volume mounts à la Docker.

This is not possible, as per firecrackers [design](https://github.com/firecracker-microvm/firecracker/blob/master/docs/design.md)

We have the possibility to do an one-time copy of files from the host to the guest with `run --copy-files`, but bidirectional volume mounts are prohibited intentionally by the security model of FC

**Comment by pditommaso** [comment]
That's a pity, didn't know about this strong requirement.

**Comment by luxas** [comment]
> That's a pity, didn't know about this strong requirement.

After talking to the Firecracker team, they said it's been very often requested, and they're considering
implementing it in the coming months/year. See: https://github.com/firecracker-microvm/firecracker/issues/1180 :sparkles:
