### ISSUE TITLE
Arm version

### ISSUE THREAD

**Issue by pbajno** [weaveworks/ignite#783]
When you will provide arm version for this? I see firecracker is compliant with arm and I am still waiting for this app to be working in this architecture.

**Comment by darkowlzz** [comment]
Hi @pbajno , ignite already has supports arm. We release arm binaries and docker image manifest list to automatically use the right image for arm. There's also a docs page describing how to use it https://ignite.readthedocs.io/en/stable/arm/ .
Hope that's helpful.
