### ISSUE TITLE
Failed to resolve docker.io

### ISSUE THREAD

**Issue by pbajno** [weaveworks/ignite#788]
Hey, I have this error which is appearing from multiple ISPs.

Ping does not work and mtr returns all nodes except the last one. Is it some kind of network filtering docker did for ddos protection? Do I have to login to get this container? Anybody have similar issue?

![image](https://user-images.githubusercontent.com/18303501/109470490-2926b980-7a78-11eb-8501-8317a69c6457.png)

**Comment by darkowlzz** [comment]
Hi, the image `weaveworks/ignite:dev` is the ignite sandbox image and is used by ignite when you build it locally. The local build created the image with `dev` tag and stores in the local container image store. If you're using the latest release binary of ignite, that'll use the image `weaveworks/ignite:v0.8.0` by default.

While doing local builds, you can run `make` to build the ignite binary and the sandbox container image it needs with `dev` tag. You can pass the flag `--sandbox-image` to `ignite run` and explicitly set the sandbox image in case you don't want to use the default sandbox. For example:

```console
# ignite run weaveworks/ignite-ubuntu --name my-vm --ssh --sandbox-image=weaveworks/ignite:v0.8.0
INFO[0000] Created VM with ID "7a468f1d68db2e65" and name "my-vm"
INFO[0001] Pulling image "weaveworks/ignite:v0.8.0"...
INFO[0009] Networking is handled by "cni"
INFO[0009] Started Firecracker VM "7a468f1d68db2e65" in a container with ID "ignite-7a468f1d68db2e65"
```

Hope that helps.

**Comment by pbajno** [comment]
That helped. Thank you.
