### ISSUE TITLE
Consider adding support for bridge-less networking

### ISSUE THREAD

**Issue by networkop** [weaveworks/ignite#831]
Hi 👋 , would you consider adding support for bridgeless networking using [tc redirect](https://github.com/awslabs/tc-redirect-tap), similar to what [kata containers](https://github.com/kata-containers/documentation/blob/master/design/architecture.md#networking) and [fircracker-containerd](https://github.com/firecracker-microvm/firecracker-containerd/blob/main/docs/networking.md#a-preferred-traffic-control) are doing?
The use case is launching VMs either without any interface config or mounting/copying configuration files into the VM filesystem and activating them on boot with something like [ifreload](https://github.com/CumulusNetworks/ifupdown2), although ultimately it'll be down to the guest image to make sure this runs.

Implementation-wise, it could a simple check that in the [networking setup](https://github.com/weaveworks/ignite/blob/main/pkg/container/network.go#L62) for loop for any configured IP addresses. If there are more than 1, then use the existing bridge+dhcp approach; if not -- setup a tc redirect between the veth and tap links. 

I'd be happy to volunteer to do a PR, assuming this is deemed acceptable.

**Comment by darkowlzz** [comment]
Implemented in #836
