### ISSUE TITLE
Change dhcp.hostname value

### ISSUE THREAD

**Issue by networkop** [weaveworks/ignite#851]
[At the moment](https://github.com/weaveworks/ignite/blob/main/pkg/container/dhcp.go#L31) VM's hostnames are set to the value of their UUID which is not human-readable.

```
// Set the VM hostname to the VM ID
dhcpIface.Hostname = vm.GetUID().String()
```

How about we change this to `vm.Name` instead to make things more human-friendly?

**Comment by darkowlzz** [comment]
I believe this behavior is based on docker's behavior
```console
$ docker run --rm -ti ubuntu bash
root@9a98cec1e940:/#
```

**Comment by networkop** [comment]
ok, makes sense
